// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpafyuhgipahfcycwpva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYWZ5dWhnaXBhaGZjeWN3cHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMjQ0MDksImV4cCI6MjA1MjgwMDQwOX0.ktIrkfK0z_HKc3fcIJKMKcxk5AL6tQv1trzKamM4oRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);